sudo: required
 
language: java
 
jdk: openjdk11
 
# cache the build tool's caches
cache:
  directories:
  - $HOME/.m2
 
script: 
  - mvn -f org.module.eer.project/pom.xml --quiet clean install

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep-history: false
  local-dir: org.module.eer.project/releng/org.module.eer.project.update/target/repository
  target-branch: gh-pages  
  verbose: true
  on:
    branch: master